services:
  - type: web
    name: academiahelper
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node server.js
    routes:
      - type: rewrite
        source: /*
        destination: /index.html