services:
  - type: web
    name: academiahelper
    env: node
    buildCommand: npm install && npm run build && cp dist/index.html dist/404.html
    startCommand: npm run preview -- --host
    envVars:
      - key: NODE_ENV
        value: production
    headers:
      - path: /*
        name: X-Robots-Tag
        value: all
    routes:
      - type: rewrite
        source: /*
        destination: /index.html